credentials:
  username: username
  password: password
API_KEY: API-KEY
urls:
  login_url: https://www.linkedin.com/feed/
  fetch_url: https://www.linkedin.com/login

settings:
  timeout: 30

topics: []
blacklist: []
stalklist: []
extensions: ['all','comments','reactions']
PORT: 5000
posts_to_load: 5
