credentials:
  username: uki.mar@gmail.com
  password: uip3EMAp@aeMA!&

urls:
  login_url: https://www.linkedin.com/feed/
  fetch_url: https://www.linkedin.com/login

settings:
  timeout: 30

topics: "Any topic"
